[package]
name = "phphp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="phphp"

[dependencies]
clap = "3.1.12"
log = "0.4.16"
